name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Determine Dockerfile path
          id: docker file
          run: echo "::set-output name=path::$(find . -type f -name Dockerfile | head -n 1)"
    

        - name: Login to Docker hub
          uses: docker/login-action@v1
          with:

            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ${{ steps.dockerfile.outputs.path }}
            push: true
            tags: ${{ secrets.DOCKER_USERNAME}}/postgres27:latest
                
